// lib/templates.ts — All 20+ templates and business data

export interface Template {
  id: string;
  title: string;
  industry: string;
  category: string;
  description: string;
  longDescription: string;
  price: number;
  popular: boolean;
  emoji: string;
  color: string;
  fundingTypes: string[];
  sections: string[];
  estimatedTime: string;
}

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All Templates' },
  { id: 'business-plans', label: 'Business Plans' },
  { id: 'grant-proposals', label: 'Grant Proposals' },
  { id: 'loan-proposals', label: 'Bank Loan Proposals' },
  { id: 'pitch-decks', label: 'Investor Pitch Docs' },
  { id: 'agriculture', label: 'Agricultural Plans' },
  { id: 'startup', label: 'Startup Plans' },
  { id: 'food-fashion', label: 'Food & Fashion' },
  { id: 'tech', label: 'Tech & E-commerce' },
];

export const TEMPLATES: Template[] = [
  {
    id: 'general-business-plan',
    title: 'General Business Plan',
    industry: 'All Industries',
    category: 'business-plans',
    description: 'Complete business plan suitable for any industry. Perfect for bank loans and investor pitches.',
    longDescription: 'A comprehensive, professionally structured business plan that covers every aspect of your business — from executive summary to financial projections.',
    price: 2500,
    popular: true,
    emoji: '📋',
    color: '#0A5C36',
    fundingTypes: ['Bank Loan', 'Investor', 'Grant'],
    sections: ['Executive Summary', 'Business Overview', 'Market Analysis', 'Financial Projections'],
    estimatedTime: '15 mins',
  },
  {
    id: 'grant-proposal-general',
    title: 'General Grant Proposal',
    industry: 'NGO / Government',
    category: 'grant-proposals',
    description: 'Professional grant proposal for government and NGO funding applications.',
    longDescription: 'Designed for applicants seeking government grants, foundation funding, or NGO support.',
    price: 2500,
    popular: true,
    emoji: '🏛️',
    color: '#F5A623',
    fundingTypes: ['Government Grant', 'NGO Funding'],
    sections: ['Cover Letter', 'Problem Statement', 'Budget', 'Sustainability Plan'],
    estimatedTime: '20 mins',
  },
  {
    id: 'tony-elumelu-proposal',
    title: 'Tony Elumelu Programme Plan',
    industry: 'Startup / SME',
    category: 'business-plans',
    description: 'Optimized specifically for the Tony Elumelu Foundation Entrepreneurship Programme application.',
    longDescription: 'Tailored to meet TEF requirements with all the sections judges look for.',
    price: 2500,
    popular: true,
    emoji: '🌟',
    color: '#8b5cf6',
    fundingTypes: ['TEF Grant', 'Foundation Grant'],
    sections: ['Executive Summary', 'Innovation Statement', 'Social Impact', 'Revenue Model'],
    estimatedTime: '20 mins',
  },
  {
    id: 'bank-loan-proposal',
    title: 'Bank SME Loan Proposal',
    industry: 'Finance / Banking',
    category: 'loan-proposals',
    description: 'Professional loan proposal for SME loans, business expansion, or equipment financing.',
    longDescription: 'Formatted to meet Nigerian bank requirements with cash flow forecasts and repayment plans.',
    price: 2500,
    popular: true,
    emoji: '🏦',
    color: '#3b82f6',
    fundingTypes: ['Bank Loan', 'SME Loan'],
    sections: ['Business Profile', 'Loan Request', 'Cash Flow Forecast', 'Repayment Plan'],
    estimatedTime: '20 mins',
  },
  {
    id: 'agricultural-business-plan',
    title: 'Agricultural Business Plan',
    industry: 'Agriculture',
    category: 'agriculture',
    description: 'Tailored for farmers, agro-processors, and agribusinesses seeking BOI or agricultural grants.',
    longDescription: 'Includes crop/livestock projections, land usage plans, and agro-financing specifics.',
    price: 2500,
    popular: true,
    emoji: '🌾',
    color: '#10b981',
    fundingTypes: ['BOI', 'Agricultural Grant', 'Bank Loan'],
    sections: ['Farm Overview', 'Production Plan', 'Market Access', 'Financial Projections'],
    estimatedTime: '18 mins',
  },
  {
    id: 'poultry-farming-plan',
    title: 'Poultry Farming Business Plan',
    industry: 'Poultry / Agriculture',
    category: 'agriculture',
    description: 'Complete business plan for layer and broiler poultry farming businesses.',
    longDescription: 'Covers farm setup, feed management, market sales, and financial projections for poultry farms.',
    price: 2500,
    popular: false,
    emoji: '🐔',
    color: '#f59e0b',
    fundingTypes: ['Agricultural Grant', 'BOI', 'Bank Loan'],
    sections: ['Farm Setup', 'Production Capacity', 'Feed Management', 'Financial Model'],
    estimatedTime: '15 mins',
  },
  {
    id: 'fish-farming-plan',
    title: 'Fish Farming Business Plan',
    industry: 'Aquaculture',
    category: 'agriculture',
    description: 'Comprehensive aquaculture business plan for catfish, tilapia, or other fish farming.',
    longDescription: 'Includes pond setup, stocking density, feed schedules, and marketing plan for fish farmers.',
    price: 2500,
    popular: false,
    emoji: '🐟',
    color: '#06b6d4',
    fundingTypes: ['Agricultural Grant', 'BOI'],
    sections: ['Pond Setup', 'Stocking Plan', 'Sales Channels', 'Financial Projections'],
    estimatedTime: '15 mins',
  },
  {
    id: 'fashion-business-plan',
    title: 'Fashion Business Plan',
    industry: 'Fashion & Apparel',
    category: 'food-fashion',
    description: 'Comprehensive plan for fashion designers, boutiques, and clothing businesses.',
    longDescription: 'Perfect for fashion entrepreneurs seeking loans or investor funding for their brand.',
    price: 2500,
    popular: false,
    emoji: '👗',
    color: '#ec4899',
    fundingTypes: ['Bank Loan', 'Investor', 'Grant'],
    sections: ['Brand Overview', 'Product Line', 'Target Market', 'Financial Plan'],
    estimatedTime: '15 mins',
  },
  {
    id: 'food-business-plan',
    title: 'Food Business Plan',
    industry: 'Food & Beverage',
    category: 'food-fashion',
    description: 'Business plan for restaurants, food production, catering, and food processing businesses.',
    longDescription: 'Covers NAFDAC compliance, production capacity, distribution, and menu costing.',
    price: 2500,
    popular: false,
    emoji: '🍽️',
    color: '#ef4444',
    fundingTypes: ['Bank Loan', 'Investor'],
    sections: ['Menu & Products', 'Production Plan', 'Regulatory Compliance', 'Financial Model'],
    estimatedTime: '18 mins',
  },
  {
    id: 'catering-business-plan',
    title: 'Catering Business Plan',
    industry: 'Catering / Events',
    category: 'food-fashion',
    description: 'Professional plan for catering services, event catering, and food delivery businesses.',
    longDescription: 'Includes event capacity, equipment needs, staffing, and revenue projections for caterers.',
    price: 2500,
    popular: false,
    emoji: '🥘',
    color: '#f97316',
    fundingTypes: ['Bank Loan', 'Microfinance'],
    sections: ['Service Offerings', 'Equipment List', 'Pricing Model', 'Financial Plan'],
    estimatedTime: '15 mins',
  },
  {
    id: 'beauty-business-plan',
    title: 'Beauty Business Plan',
    industry: 'Beauty & Cosmetics',
    category: 'food-fashion',
    description: 'Business plan for salons, beauty brands, skincare lines, and cosmetics businesses.',
    longDescription: 'Perfect for beauty entrepreneurs seeking funding to grow their brand or open a salon.',
    price: 2500,
    popular: false,
    emoji: '💄',
    color: '#a855f7',
    fundingTypes: ['Bank Loan', 'Women Grant'],
    sections: ['Service Menu', 'Brand Identity', 'Revenue Streams', 'Financial Projections'],
    estimatedTime: '15 mins',
  },
  {
    id: 'tech-startup-plan',
    title: 'Tech Startup Business Plan',
    industry: 'Technology / SaaS',
    category: 'tech',
    description: 'Business plan for Nigerian tech startups, SaaS products, and digital businesses.',
    longDescription: 'Investor-ready tech startup plan covering MVP, product-market fit, and scaling strategy.',
    price: 2500,
    popular: true,
    emoji: '💻',
    color: '#6366f1',
    fundingTypes: ['Investor', 'VC', 'Accelerator'],
    sections: ['Product Overview', 'Technology Stack', 'Go-to-Market', 'Financial Projections'],
    estimatedTime: '20 mins',
  },
  {
    id: 'ecommerce-business-plan',
    title: 'E-commerce Business Plan',
    industry: 'E-commerce / Retail',
    category: 'tech',
    description: 'Business plan for online stores, dropshipping, and e-commerce businesses.',
    longDescription: 'Covers platform setup, logistics, payment processing, and digital marketing for e-commerce.',
    price: 2500,
    popular: false,
    emoji: '🛒',
    color: '#0ea5e9',
    fundingTypes: ['Bank Loan', 'Investor'],
    sections: ['Product Categories', 'Platform Strategy', 'Logistics Plan', 'Revenue Model'],
    estimatedTime: '18 mins',
  },
  {
    id: 'logistics-business-plan',
    title: 'Logistics Business Plan',
    industry: 'Logistics & Transport',
    category: 'business-plans',
    description: 'Business plan for logistics, haulage, delivery, and transportation companies.',
    longDescription: 'Covers fleet management, route optimization, pricing, and growth for logistics firms.',
    price: 2500,
    popular: false,
    emoji: '🚚',
    color: '#14b8a6',
    fundingTypes: ['Bank Loan', 'BOI'],
    sections: ['Fleet Overview', 'Route Plan', 'Pricing Strategy', 'Financial Projections'],
    estimatedTime: '15 mins',
  },
  {
    id: 'real-estate-plan',
    title: 'Real Estate Business Plan',
    industry: 'Real Estate / Property',
    category: 'business-plans',
    description: 'Business plan for real estate development, rental properties, and property agents.',
    longDescription: 'Covers property acquisition, development, rental income, and ROI projections.',
    price: 2500,
    popular: false,
    emoji: '🏘️',
    color: '#64748b',
    fundingTypes: ['Bank Loan', 'Investor', 'Mortgage'],
    sections: ['Property Overview', 'Market Analysis', 'Development Plan', 'Financial Model'],
    estimatedTime: '20 mins',
  },
  {
    id: 'pos-business-plan',
    title: 'POS Business Plan',
    industry: 'Fintech / POS',
    category: 'business-plans',
    description: 'Business plan for POS terminal operators and agent banking services in Nigeria.',
    longDescription: 'Covers transaction volumes, revenue projections, and business model for POS operators.',
    price: 2500,
    popular: false,
    emoji: '💳',
    color: '#22c55e',
    fundingTypes: ['Microfinance', 'Bank Loan'],
    sections: ['POS Operations', 'Transaction Model', 'Location Strategy', 'Financial Plan'],
    estimatedTime: '12 mins',
  },
  {
    id: 'importation-business-plan',
    title: 'Importation Business Plan',
    industry: 'Import / Export',
    category: 'business-plans',
    description: 'Business plan for importation businesses, mini-importation, and wholesale trading.',
    longDescription: 'Covers sourcing, customs clearance, pricing, and sales for importation businesses.',
    price: 2500,
    popular: false,
    emoji: '📦',
    color: '#f59e0b',
    fundingTypes: ['Bank Loan', 'Trader Loan'],
    sections: ['Product Sourcing', 'Import Process', 'Distribution', 'Financial Projections'],
    estimatedTime: '15 mins',
  },
  {
    id: 'cleaning-business-plan',
    title: 'Cleaning Business Plan',
    industry: 'Cleaning Services',
    category: 'business-plans',
    description: 'Business plan for commercial and residential cleaning service companies.',
    longDescription: 'Covers service packages, equipment, staffing, and growth plan for cleaning businesses.',
    price: 2500,
    popular: false,
    emoji: '🧹',
    color: '#06b6d4',
    fundingTypes: ['Microfinance', 'Bank Loan'],
    sections: ['Service Packages', 'Equipment List', 'Pricing Model', 'Financial Plan'],
    estimatedTime: '12 mins',
  },
  {
    id: 'youth-grant-proposal',
    title: 'Youth Entrepreneurship Grant',
    industry: 'Youth / SME',
    category: 'grant-proposals',
    description: 'Grant proposal optimized for NYIF, CBN youth grants, and other youth funding schemes.',
    longDescription: 'Designed for Nigerian youth entrepreneurs seeking NYIF and similar government funding.',
    price: 2500,
    popular: true,
    emoji: '👨‍🎓',
    color: '#0A5C36',
    fundingTypes: ['NYIF', 'Youth Grant'],
    sections: ['Applicant Profile', 'Business Idea', 'Social Impact', 'Budget'],
    estimatedTime: '18 mins',
  },
  {
    id: 'women-grant-proposal',
    title: "Women Entrepreneur Grant",
    industry: "Women's Business",
    category: 'grant-proposals',
    description: "Grant proposal for women entrepreneurs seeking women-focused grants and funding.",
    longDescription: 'Tailored for women seeking grants from government programmes and international organisations.',
    price: 2500,
    popular: false,
    emoji: '👩‍💼',
    color: '#ec4899',
    fundingTypes: ["Women's Grant", 'Government Grant'],
    sections: ['Applicant Profile', 'Business Concept', 'Community Impact', 'Budget'],
    estimatedTime: '18 mins',
  },
  {
    id: 'investor-pitch-deck',
    title: 'Investor Pitch Document',
    industry: 'Startup / Growth',
    category: 'pitch-decks',
    description: 'Compelling investor pitch document for raising equity funding or venture capital.',
    longDescription: 'Structured like a pitch deck in document form — problem, solution, traction, and ask.',
    price: 2500,
    popular: true,
    emoji: '📊',
    color: '#6366f1',
    fundingTypes: ['VC', 'Angel Investment', 'Private Equity'],
    sections: ['Problem & Opportunity', 'Solution', 'Traction', 'Team', 'Financial Ask'],
    estimatedTime: '20 mins',
  },
];

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): Template[] {
  if (category === 'all') return TEMPLATES;
  return TEMPLATES.filter((t) => t.category === category);
}

export const NIGERIAN_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
  'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT (Abuja)',
  'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi',
  'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo',
  'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
];

export const BUSINESS_TYPES = [
  'Sole Proprietorship', 'Partnership', 'Limited Liability Company (LLC)',
  'Private Limited Company (Ltd)', 'Non-Governmental Organisation (NGO)',
  'Cooperative Society', 'Social Enterprise',
];

export const INDUSTRIES = [
  'Agriculture & Agribusiness', 'Automobile & Transport', 'Beauty & Cosmetics',
  'Construction & Real Estate', 'Education & Training', 'E-commerce & Retail',
  'Fashion & Apparel', 'Finance & Fintech', 'Food & Beverage',
  'Healthcare & Pharmaceuticals', 'Hospitality & Tourism', 'ICT & Technology',
  'Importation & Trade', 'Logistics & Delivery', 'Manufacturing & Production',
  'Media & Entertainment', 'Oil & Gas', 'Poultry & Livestock',
  'Professional Services', 'Social Enterprise & NGO',
];

export const FUNDING_TYPES = [
  'Bank SME Loan', 'Government Grant', 'Foundation Grant', 'NGO Funding',
  'Angel Investment', 'Venture Capital (VC)', 'Personal Savings', 'Family & Friends',
  'Cooperative Loan', 'Microfinance Loan', 'BOI Loan', 'NYIF', 'TEF Grant',
];

export const SPENDING_CATEGORIES = [
  'Equipment & Machinery', 'Marketing & Advertising', 'Inventory & Stock',
  'Staff Salaries', 'Rent & Utilities', 'Raw Materials', 'Vehicle & Transport',
  'Technology & Software', 'Working Capital', 'Renovation & Infrastructure',
  'Legal & Registration', 'Training & Development',
];
