'use client';

import { useState, useEffect, useMemo } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FileText, Plus, LogOut, Loader2, Download, Eye, Search, Trash2 } from 'lucide-react';
import { useAuth } from '@/components/auth/AuthProvider';
import { getUserDocuments, getUserSubscription, signOut, deleteDocument } from '@/lib/supabase';
import { Document } from '@/lib/database.types';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import styles from './dashboard.module.css';

export default function DashboardPage() {
  const { user, isLoading: isAuthLoading } = useAuth();
  const [documents, setDocuments] = useState<Document[]>([]);
  const [subscription, setSubscription] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [search, setSearch] = useState('');
  const router = useRouter();

  useEffect(() => {
    if (!isAuthLoading && !user) {
      router.push('/login');
    }
  }, [user, isAuthLoading, router]);

  useEffect(() => {
    async function loadData() {
      if (user) {
        const [{ data: docs }, { data: sub }] = await Promise.all([
          getUserDocuments(user.id),
          getUserSubscription(user.id)
        ]);
        if (docs) setDocuments(docs);
        if (sub) setSubscription(sub);
        setIsLoading(false);
      }
    }
    loadData();
  }, [user]);

  const handleSignOut = async () => {
    await signOut();
    router.push('/');
    router.refresh();
  };

  const handleDelete = async (id: string) => {
    if (confirm('Are you sure you want to delete this document?')) {
      const { error } = await deleteDocument(id);
      if (!error) {
        setDocuments(documents.filter((doc) => doc.id !== id));
      } else {
        alert('Failed to delete document: ' + error.message);
      }
    }
  };

  const handleDownloadPDF = (doc: Document) => {
    const content = (doc as any).content;
    if (!content) { alert('No content to download.'); return; }
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    const htmlContent = content
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/^---$/gm, '<hr/>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>.+<\/li>\n?)+/g, (m: string) => `<ul>${m}</ul>`)
      .replace(/\n\n/g, '</p><p>');

    printWindow.document.write(`<!DOCTYPE html><html><head>
      <title>${doc.business_name || 'Business Plan'} - BizPlan Nigeria</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Inter',sans-serif; max-width: 820px; margin: 0 auto; padding: 48px 56px; color: #1a1a2e; line-height: 1.75; }
        h1 { color: #0A5C36; font-size: 2rem; border-bottom: 3px solid #F5A623; padding-bottom: 12px; margin-bottom: 24px; }
        h2 { color: #0A5C36; font-size: 1.35rem; margin-top: 2rem; margin-bottom: 10px; }
        p { margin-bottom: 14px; color: #374151; }
        ul { margin: 0 0 16px 24px; }
        li { margin-bottom: 6px; color: #374151; }
        strong { color: #0A5C36; font-weight: 700; }
        hr { border: none; border-top: 2px solid #e5e7eb; margin: 2rem 0; }
        .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 12px; color: #9ca3af; }
        @media print { body { padding: 24px 32px; } }
      </style></head><body>
      ${htmlContent}
      <div class="footer">Generated by BizPlan Nigeria | bizplannigeria.com</div>
    </body></html>`);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 600);
  };

  const filteredDocuments = useMemo(() =>
    documents.filter(doc =>
      !search ||
      doc.business_name?.toLowerCase().includes(search.toLowerCase()) ||
      doc.template_title?.toLowerCase().includes(search.toLowerCase())
    ), [documents, search]);

  if (isAuthLoading || (isLoading && user)) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
        <Loader2 size={48} className="spinner" style={{ color: 'var(--color-primary)' }} />
      </div>
    );
  }

  if (!user) return null;

  return (
    <>
      <Navbar />
      <main className={styles.dashboardPage}>
        <div className="container">
          <div className={styles.dashboardHeader}>
            <div>
              <h1 className={styles.dashboardTitle}>Welcome back, {user.user_metadata?.full_name?.split(' ')[0] || 'Entrepreneur'} 👋</h1>
              <p className={styles.dashboardSubtitle}>Manage your business documents and proposals.</p>
            </div>
            <div className={styles.headerActions}>
              <Link href="/templates" className="btn btn-primary">
                <Plus size={16} /> New Document
              </Link>
              <button onClick={handleSignOut} className="btn btn-outline">
                <LogOut size={16} /> Sign Out
              </button>
            </div>
          </div>

          {/* Stats */}
          <div className="grid-3" style={{ marginBottom: 'var(--space-2xl)' }}>
            <div className="stat-card">
              <div className="stat-card-icon" style={{ background: 'var(--color-primary-50)', color: 'var(--color-primary)' }}>
                <FileText size={24} />
              </div>
              <div className="stat-card-value">{documents.length}</div>
              <div className="stat-card-label">Total Documents</div>
            </div>
            <div className="stat-card">
              <div className="stat-card-icon" style={{ background: 'var(--color-primary-50)', color: 'var(--color-primary)' }}>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"></polygon></svg>
              </div>
              <div className="stat-card-value" style={{ textTransform: 'capitalize' }}>
                {subscription?.plan || 'Free Plan'}
              </div>
              <div className="stat-card-label">
                {subscription ? `Active Subscription` : <Link href="/pricing" style={{ color: 'var(--color-primary)' }}>Upgrade to Pro</Link>}
              </div>
            </div>
            <div className="stat-card">
              <div className="stat-card-icon" style={{ background: 'var(--color-primary-50)', color: 'var(--color-primary)' }}>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2L13.5 9H21L15 13.5L17.5 21L12 16.5L6.5 21L9 13.5L3 9H10.5L12 2Z"/></svg>
              </div>
              <div className="stat-card-value">{documents.filter(d => d.status === 'completed').length}</div>
              <div className="stat-card-label">Completed Plans</div>
            </div>
          </div>

          {/* Documents Table */}
          <div className="card">
            <div className="card-header" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
              <h3 style={{ fontFamily: 'var(--font-sans)', fontSize: '1.125rem' }}>Your Documents</h3>
              {documents.length > 0 && (
                <div className={styles.searchWrapper}>
                  <Search size={15} className={styles.searchIcon} />
                  <input
                    type="search"
                    className="form-input"
                    placeholder="Search documents..."
                    value={search}
                    onChange={e => setSearch(e.target.value)}
                    style={{ paddingLeft: '34px', width: 220, fontSize: '0.9rem' }}
                  />
                </div>
              )}
            </div>
            
            {documents.length === 0 ? (
              <div className={styles.emptyState}>
                <div style={{ fontSize: '3rem', marginBottom: '16px' }}>📄</div>
                <h3>No documents yet</h3>
                <p>You haven&apos;t created any business plans or proposals yet.</p>
                <Link href="/templates" className="btn btn-primary" style={{ marginTop: '16px' }}>
                  Create Your First Document
                </Link>
              </div>
            ) : filteredDocuments.length === 0 ? (
              <div className={styles.emptyState}>
                <div style={{ fontSize: '2rem', marginBottom: '12px' }}>🔍</div>
                <h3>No results for &quot;{search}&quot;</h3>
                <p>Try a different search term.</p>
              </div>
            ) : (
              <div className="table-wrapper">
                <table>
                  <thead>
                    <tr>
                      <th>Document</th>
                      <th>Type</th>
                      <th>Status</th>
                      <th>Last Updated</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredDocuments.map((doc) => (
                      <tr key={doc.id}>
                        <td>
                          <div style={{ fontWeight: 600 }}>{doc.business_name || doc.template_title}</div>
                        </td>
                        <td>
                          <span className="badge badge-primary">{doc.template_title}</span>
                        </td>
                        <td>
                          <span className={`badge ${doc.status === 'completed' ? 'badge-success' : 'badge-accent'}`}>
                            {doc.status}
                          </span>
                        </td>
                        <td style={{ fontSize: '0.875rem', color: 'var(--color-text-muted)' }}>
                          {new Date(doc.updated_at).toLocaleDateString('en-NG')}
                        </td>
                        <td>
                          <div style={{ display: 'flex', gap: '8px' }}>
                            <Link href={`/dashboard/document/${doc.id}`} className="btn btn-ghost btn-sm" title="View Document">
                              <Eye size={15} />
                            </Link>
                            <button
                              className="btn btn-ghost btn-sm"
                              title="Download PDF"
                              onClick={() => handleDownloadPDF(doc)}
                            >
                              <Download size={15} />
                            </button>
                            <button
                              onClick={() => handleDelete(doc.id)}
                              className="btn btn-ghost btn-sm"
                              style={{ color: 'var(--color-danger)' }}
                              title="Delete"
                            >
                              <Trash2 size={15} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
